// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Context.Migrations
{
    [DbContext(typeof(SolutionContext))]
    [Migration("20190119213211_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.ManualMovement.ManualMovement", b =>
                {
                    b.Property<int>("ManualMovementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Description");

                    b.Property<DateTime>("ModifieldDate");

                    b.Property<int>("Month");

                    b.Property<int>("ProductCosifId");

                    b.Property<int>("ProductId");

                    b.Property<decimal>("Value");

                    b.Property<int>("Year");

                    b.HasKey("ManualMovementId");

                    b.HasIndex("ProductCosifId");

                    b.HasIndex("ProductId");

                    b.ToTable("ManualMovements");
                });

            modelBuilder.Entity("Model.Product.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Description");

                    b.Property<DateTime>("ModifieldDate");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Model.Product.ProductCosif", b =>
                {
                    b.Property<int>("ProductCosifId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodProductCosif");

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime>("ModifieldDate");

                    b.HasKey("ProductCosifId");

                    b.ToTable("ProductCosif");
                });

            modelBuilder.Entity("Model.ManualMovement.ManualMovement", b =>
                {
                    b.HasOne("Model.Product.ProductCosif", "ProductCosif")
                        .WithMany()
                        .HasForeignKey("ProductCosifId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Model.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
